baseURL = 'https://example.com/'
languageCode = 'en-us'
title = "Green Phoenix Designs"

[params]
  bookURL = 'https://book.squareup.com/appointments/01urh26tbu02ur/location/LNADDS0WZHSAW/services/2ZNPFJBWV3B226ZI53NLNOCA'
  followupURL = 'https://book.squareup.com/appointments/xz89zihwrz016u/location/LNADDS0WZHSAW/services/OZMO6EQE2QQ2DEKB3Z4HBO3C'

[markup.goldmark.renderer]
unsafe = true

[menu]
  [[menu.main]]
    name = 'Book Consultation'
    url = 'https://book.squareup.com/appointments/01urh26tbu02ur/location/LNADDS0WZHSAW/services/2ZNPFJBWV3B226ZI53NLNOCA'
    weight = 1
  [[menu.main]]
    name = 'About Us'
    url = '/#about'
    weight = 10
  [[menu.main]]
    name = 'Services'
    pageRef = '/services'
    weight = 20
  [[menu.main]]
    name = 'Newsletter'
    pageRef = '/newsletter'
    weight = 50
  [[menu.main]]
    name = 'Careers'
    pageRef = '/careers'
    weight = 60
  [[menu.main]]
    name = 'Contact'
    pageRef = '/contact'
    weight = 70
