baseURL = 'https://example.com/'
languageCode = 'en-us'
title = "Green Phoenix Designs"

[markup.goldmark.renderer]
unsafe = true

[menu]
  [[menu.main]]
    name = 'Book Consultation'
    pageRef = '/book'
    weight = 1
  [[menu.main]]
    name = 'About'
    url = '/#about'
    weight = 10
  [[menu.main]]
    name = 'Services'
    url = '/#services'
    weight = 20
  [[menu.main]]
    name = 'Testimonials'
    url = '/#testimonials'
    weight = 40
  [[menu.main]]
    name = 'Newsletter'
    pageRef = '/newsletter'
    weight = 50
  [[menu.main]]
    name = 'Careers'
    pageRef = '/careers'
    weight = 60
  [[menu.main]]
    name = 'Instagram'
    url = 'https://www.instagram.com/greenphoenixdesigns'
    weight = 70
