baseURL = 'https://example.com/'
languageCode = 'en-us'
title = "Green Phoenix Designs"

[markup.goldmark.renderer]
unsafe = true

[menu]
  [[menu.main]]
    name = 'Book Consultation'
    pageRef = '/book'
    weight = 1
  [[menu.main]]
    name = 'About Us'
    url = '/#about'
    weight = 10
  [[menu.main]]
    name = 'Services'
    pageRef = '/services'
    weight = 20
  [[menu.main]]
    name = 'Newsletter'
    pageRef = '/newsletter'
    weight = 50
  [[menu.main]]
    name = 'Careers'
    pageRef = '/careers'
    weight = 60
  [[menu.main]]
    name = 'Contact'
    pageRef = '/contact'
    weight = 70
