backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: static/img
public_folder: /img
collections:
  - name: 'Pages'
    label: 'pages'
    files:
      - file: 'content/gallery/_index.md'
        label: 'Project gallery'
        name: 'gallery'
        fields:
        - label: 'Photos'
          name: 'photos'
          widget: 'list'
          fields:
            - { label: 'Image', name: 'file_url', widget: 'image' }
            - { label: 'Caption', name: 'caption', widget: 'string' }
