backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: static/img
public_folder: /img
collections:
  - label: 'Services'
    name: 'services'
    file: 'content/services.md'
    fields:
      - { label: 'Name', name: 'name', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Photo', name: 'photo_url', widget: 'image' }
  - label: 'Careers'
    name: 'careers'
    folder: 'content/careers'
    filter: {field: visibleInCMS, value: true}
    create: true
    fields:
      - { label: 'Job Title', name: 'title', widget: 'string' }
      - { label: 'Job description', name: 'body', widget: 'markdown' }
      - { label: 'Link to application form', name: 'apply_link', widget: 'string' }
      - { name: visibleInCMS, widget: hidden, default: true, i18n: duplicate}
