backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: static/img
public_folder: /img
collections:
  - label: 'Pages'
    name: 'pages'
    files:
      - label: 'Homepage'
        name: 'home'
        file: 'content/_index.md'
        fields:
          - { label: 'About Us', name: 'body', widget: 'text' }
  - label: 'Services'
    name: 'services'
    folder: 'content/services'
    filter: {field: visibleInCMS, value: true}
    create: true
    fields:
      - { label: 'Service name', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Order of appearance', name: 'order', widget: 'number' }
      - { label: 'Photo', name: 'photo_url', widget: 'image' }
      - { name: visibleInCMS, widget: hidden, default: true, i18n: duplicate}
  - label: 'Careers'
    name: 'careers'
    folder: 'content/careers'
    filter: {field: visibleInCMS, value: true}
    create: true
    fields:
      - { label: 'Job Title', name: 'title', widget: 'string' }
      - { label: 'Job description', name: 'body', widget: 'markdown' }
      - { label: 'Link to application form', name: 'apply_link', widget: 'string' }
      - { name: visibleInCMS, widget: hidden, default: true, i18n: duplicate}
